### ISSUE TITLE
Create urdf.xacro file for Gigatron with race body

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#11]
The current [`gigatron.urdf.xacro`](https://github.com/5yler/metatron/blob/f8f90285b412a6d7334a31efd249956d14a79afe/gigatron_hardware/urdf/gigatron.urdf.xacro) has sensor mounting and car dimensions specific to the test hardware mounting without the race body.
# Tasks
- [x] modify `imu_link` with final IMU mount location for race
- [x] modify `laser_link` with final RPLIDAR mount location for race
- [x] add `back_laser_link` if using a second LIDAR mounted on the rear of the car
