### ISSUE TITLE
Use EKF for filtered odometry

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#15]
Branched off from Issue #9. I think that  in order to use `ekf_localization_node` in the `odom` frame, we would have to disable the `odom->base_link` transform broadcast by `odom_tf_publisher`, which currently both:
- publishes to the `odom` topic 
- broadcasts the transform `odom->base_link`

See [Using robot_localization with amcl (ROS Answers)](http://answers.ros.org/question/218137/using-robot_localization-with-amcl/)
## Tasks
- [ ] add parameter to `odom_tf_publisher` to disable broadcasting `odom->base_link` transform
- [ ] run `ekf_odom.launch` with modified `odom_tf_publisher` and collect rosbag data
- [ ] compare accuracy of `odom->base_link` transform with previous results
