### ISSUE TITLE
Fix drive script

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#17]
Currently throws a lot of `nan` outputs for steering angle and wheel velocities. Also does not account for LIDAR orientation.
# Tasks
- [x] fix `nan` outputs
- [x] remove laser scan parameter hardcoding
- [x] adapt `drive` to account for LIDAR yaw angle
  - [x] optionally with `tf` listener
  - [x] alternatively with parameter for constant offset angle
