### ISSUE TITLE
Create new LaserScan angle filter for inverted lasers

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#19]
The `laser_filters` package `LaserScanAngularBoundsFilter` implementation allows filtering between a `lower_angle` and `upper_angle` value, but assumes `lower_angle < upper_angle`.

This doesn't work with the RPLIDAR if rotated 180 degrees, since `angle_min = -pi` and `angle_max = pi` and the points we want to keep for the forward facing 180 degrees would lie on the two intervals `[-pi, -pi/2]` and `[pi/2, pi]`
# Tasks
- [x] implement new scan filter that allows throwing the middle points rather than the two side intervals
- [x] replace launch occurrences of the `LaserScanAngularBoundsFilter` with the new `LaserScanAngleFilter` implementation as needed
  - [x] XV LIDAR on the front of Gigatron
  - [x] RPLIDAR on the front of Gigatron (depending on final mounting configuration)
