### ISSUE TITLE
Implement curb detection

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#21]
![image](https://cloud.githubusercontent.com/assets/10868851/18771253/65b5717c-810b-11e6-8c66-c5ee36d50151.png)

New York Maker Faire track might not have solid barriers all around. Possible solutions:
- downward-tilted LIDAR
- ZED stereo camera

The ZED could be integrated with [depthimage_to_laserscan](http://wiki.ros.org/depthimage_to_laserscan) or [pointcloud_to_laserscan](http://wiki.ros.org/pointcloud_to_laserscan). The latter is less efficient but seems to allow conversion between frames, which would allow greater flexibility in sensor mounting.
# Tasks
- [x] update `gigatron.urdf.xacro` to include: 
  - [x] ZED
  - [x] upside-down XV LIDAR on front of car
  - [x] IMU mount location
- [ ] update `gigatron.launch` to apply appropriate laser angle filters
- [ ] rewrite `pointcloud_to_scan.launch` to take max, min height parameters, output scan topic name, and output `frame_id`
