### ISSUE TITLE
Integrate ZED with hardware and navigation launch files

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#22]
From the [ZED ROS wrapper wiki page](http://wiki.ros.org/zed-ros-wrapper):

> The ZED Stereo Camera is a lightweight depth camera based on passive stereo vision. It outputs up to 2208x1242 high-resolution stereo video on USB 3.0, and can work in high-speed mode in VGA at 100 FPS. The ZED SDK computes a depth map of the environment on the GPU of the host machine at the frame rate of the camera. It also gives you access to a strong odometry that learn its environment, making it able to relocate itself at any moment.
> 
> ![image](https://cloud.githubusercontent.com/assets/10868851/18771700/f05ca658-810e-11e6-80e8-fede801757bc.png)
# Tasks
- [x] add ZED launch file to `gigatron_hardware`
- [ ] integrate ZED odometry with `ekf_map.launch`
- [x] create launch file for [`rtabmap_ros`](http://wiki.ros.org/rtabmap_ros) RGB-D SLAM
