### ISSUE TITLE
Create individual car component URDF macros

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#23]
The end result will be that the car `.urdf.xacro` files are less cluttered, and the sensor placement is easier to modify.
# Tasks
- [x] `zed.urdf.xacro` 
- [x] `bno055_imu.urdf.xacro` 
- [x] `rplidar.urdf.xacro` 
- [x] `xvlidar.urdf.xacro` 
- [ ] `wheel.urdf.xacro` 
- [ ] `base.urdf.xacro`
