### ISSUE TITLE
Avoid driving straight into walls

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#26]
Currently, the reactive steering algorithm in `drive` only outputs a nonzero steering angle when there are more obstacles on one side of the car. If the car is driving straight into a wall, it won't stop.

Add some logic to check if it's approaching a flat/even obstacle ahead, then slow down and turn if that's the case.

## Tasks
- [x] test RPLIDAR-based estop
- [ ] implement laser filter with narrower angle for estop
- [ ] modify gigabug code to allow estop testing in SEMIAUTOMATIC mode
