### ISSUE TITLE
Modify drive message format and visualization marker display

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#27]
The output of `drive` is a `Gigatron/Drive` message. Switch to `DriveStamped` to allow for viewing the commands generated from bagged data.

Currently `arduino_drive_controller` handles semiautomatic mode and autonomous mode as equivalent. 
# Tasks
- [x] define new message type
  - [x] change output message format in `drive` script
  - [x] change `Drive` callback in `arduino_drive_controller`
- [x] modify `arduino_drive_controller` so that all three modes are visually distinct
- [x] propagate timestamps from messages received in `arduino_drive_controller`
