### ISSUE TITLE
Calibrate IMU on both cars

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#3]
See the [Calibration](https://github.com/romainreignier/rtimulib_ros/blob/master/README.md#calibration) section of the `README.md` in [`rtimulib_ros`](https://github.com/romainreignier/rtimulib_ros/):

> ## Calibration
> 
> The calibration needs to be performed by the `RTIMULibCal` utility provided by the library.
> In case of a several devices configuration, `RTIMULibCal` can be launched with an argument to change the name of the calibration file.
> Example:
> 
> ```
>    $ RTIMULibCal toto
> ```
> 
> Will produce the `toto.ini` file in the current directory.
> 
> Then, the file calibration file `.ini` needs to be placed in the `config` directory of the package.
> 
> If the calibration file has a custom name, it must be specified with the `calibration_file_name` parameter. 

We probably want to save the `.ini` files in `gigatron_hardware/config/<CAR_NAME>/imu_calibration.ini` or something like that
## Tasks
- [ ] calibrate IMU 
  - [ ] Gigatron
    - [x] accelerometer
    - [ ] magnetometer
  - [x] Kilotron
    - [x] accelerometer 
    - [x] magnetometer 
      - [x] maybe someone without a shitton of metal on both writsts?
- [x] check if calibration file can be loaded from custom path (i.e. from inside `gigatron_hardware`) using the `calibration_file_path` parameter
- [ ] commit calibration results
  - [ ] Gigatron
  - [x] Kilotron
- [x] update `imu.launch` to account for new calibration files on both cars
