### ISSUE TITLE
Account for motor RPM limits when publishing Arduino

### ISSUE THREAD

**Issue by 5yler** [5yler/metatron#4]
Right now, [the `arduino_drive_controller` node](https://github.com/5yler/metatron/blob/master/gigatron_hardware/src/arduino_drive_controller.cpp#L99) directly converts desired wheel velocities into motor RPM without accounting for motor RPM limits:

```
      cmd_msg_.rpm_left = msg->vel_left / (_rpm_to_vel * _gear_ratio);
      cmd_msg_.rpm_right = msg->vel_right / (_rpm_to_vel * _gear_ratio);
```
## Tasks
- [ ] determine maximum motor RPM 
  - [x] Kilotron
  - [ ] Gigatron
- [ ] save maximum RPM values into `gigatron_hardware/config/<CAR>_platform.yaml` as a new `max_motor_rpm` parameter
- [x] modify `arduino_drive_controller` to read in the new parameter
- [ ] add logic to clip the commands at the motor RPM range limits
